[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r fittrack-backend/requirements.txt"
]

[phases.build]
cmds = ["python fittrack-backend/manage.py collectstatic --noinput"]

[start]
cmd = "python fittrack-backend/manage.py migrate && gunicorn --chdir fittrack-backend fittrack.wsgi --bind 0.0.0.0:$PORT"