# Generated by Django 4.2.7 on 2025-10-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(choices=[('Arms', 'Arms'), ('Legs', 'Legs'), ('Chest', 'Chest'), ('Back', 'Back'), ('Abs', 'Abs')], max_length=20)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
